[package]
name = "retrom-service"
resolver = "2"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "The Retrom video game library service"

[dependencies]
retry = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
deadpool = { workspace = true }
retrom-db = { workspace = true }
retrom-codegen = { workspace = true }
retrom-service-common = { workspace = true }
retrom-telemetry = { workspace = true }
retrom-grpc-service = { workspace = true }
retrom-rest-service = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
tower = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http = { workspace = true }
config = { workspace = true }
opentelemetry-otlp = { workspace = true }

[target.'cfg(not(windows))'.dependencies]
signal-hook = { workspace = true }
signal-hook-tokio = { workspace = true }

[features]
embedded_db = ["retrom-db/embedded"]
