[package]
name = "retrom-webdav-service"
resolver = "2"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "The Retrom video game library WebDAV service handlers"

[dependencies]
thiserror = { workspace = true }
http = { workspace = true }
retrom-codegen = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
retrom-service-common = { workspace = true }
retrom-telemetry = { workspace = true }
dav-server = "0.8.0"
hyper = { workspace = true }
hyper-util = { workspace = true }
axum = { workspace = true }
axum-tracing-opentelemetry = { workspace = true }
