name: Build Client

on:
  workflow_call:
    outputs:
      bundles:
        value: ${{ jobs.build.outputs.bundles }}
        description: The resultant bundles, if applicable
      binary:
        value: ${{ jobs.build.outputs.binary }}
        description: The resultant build binary
      web-dist:
        value: ${{ jobs.build.outputs.web-dist }}
        description: The static web assets for this build
      cargo-deps:
        value: ${{ jobs.build.outputs.cargo-deps }}
        description: The vendored cargo dependencies for this build
    inputs:
      bundle:
        type: boolean
        default: false
      sign:
        type: boolean
        default: true
      os:
        required: true
        type: string
      target:
        type: string
      debug:
        type: boolean
        default: false
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: true
      UPTRACE_DSN:
        required: true
      OTEL_EXPORTER_OTLP_HEADERS:
        required: true
      TAURI_SIGNING_PRIVATE_KEY:
        required: false
      APPLE_CERTIFICATE:
        required: false
      APPLE_CERTIFICATE_PASSWORD:
        required: false
      APPLE_SIGNING_IDENTITY:
        required: false
      APPLE_ID:
        required: false
      APPLE_PASSWORD:
        required: false
      APPLE_TEAM_ID:
        required: false
      APPLE_API_KEY:
        required: false
      APPLE_API_ISSUER:
        required: false

  workflow_dispatch:
    inputs:
      bundle:
        type: boolean
        default: false
        description: Create native bundles (e.g. `.app` for MacOS, `.deb|.rpm|.appimage` for linux)
      sign:
        type: boolean
        default: true
        description: Sign any created bundles
      os:
        required: true
        type: choice
        options:
          - macos-latest
          - windows-latest
          - ubuntu-24.04
          - ubuntu-24.04-arm
        description: |
          The OS that this build job will be run on. Must be one of: 
          'macos-latest', 'windows-latest', 'ubuntu-24.04', 'ubuntu-24.04-arm'
      target:
        type: choice
        options:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        description: |
          The target to build for on multi-target platforms, must be one of: 
          'aarch64-apple-darwin', 'x86_64-apple-darwin'
      debug:
        type: boolean
        default: false
        description: Create debug builds

permissions:
  contents: read

env:
  PQ_LIB_STATIC: 1
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  TARGET_ARG: ${{ format('{0}{1}', inputs.target && '--target ' || '', inputs.target) }}
  BUNDLE_ARG: ${{ !inputs.bundle && '--no-bundle' || '' }}
  SIGN_ARG: ${{ !inputs.sign && '--no-sign' || '' }}
  OUT_DIR: "/target"
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
  APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
  ARTIFACT_PREFIX: ""

jobs:
  build:
    runs-on: ${{ inputs.os }}
    outputs:
      bundles: steps.bundle.outputs
      binary: steps.binary.outputs
      web-dist: steps.web-dist.outputs
      cargo-deps: steps.cargo-deps.outputs
    steps:
      - name: Configure job
        shell: bash
        env:
          TARGET: ${{ inputs.target }}
          PROFILE: ${{ inputs.debug && 'debug' || 'release' }}
          INPUTS_JSON: ${{ toJson(inputs) }}
        run: |
          export ARTIFACT_PREFIX="${{ inputs.os }}-"

          if [ -n "$TARGET" ]; then
            export TARGET_DIR="target/$TARGET"
            export ARTIFACT_PREFIX="${ARTIFACT_PREFIX}${TARGET}-"
          else
            export TARGET_DIR="target"
          fi

          export OUT_DIR="$TARGET_DIR/$PROFILE"
          echo "OUT_DIR=$OUT_DIR" >> "$GITHUB_ENV"
          echo "ARTIFACT_PREFIX=$ARTIFACT_PREFIX" >> "$GITHUB_ENV"

          echo inputs: "$INPUTS_JSON"
          echo ARGS: "$TARGET_ARG $BUNDLE_ARG $SIGN_ARG"
          echo OUT_DIR: "$OUT_DIR"
          echo ARTIFACT_PREFIX: "$ARTIFACT_PREFIX"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: install Rust stable
        id: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ inputs.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: false
          cache-all-crates: false
          cache-workspace-crates: true

      - name: install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install dependencies (ubuntu 24 only)
        if: startsWith(inputs.os, 'ubuntu-24.04')
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libwebkit2gtk-4.1-0=2.44.0-2 \
            libwebkit2gtk-4.1-dev=2.44.0-2 \
            libjavascriptcoregtk-4.1-0=2.44.0-2 \
            libjavascriptcoregtk-4.1-dev=2.44.0-2 \
            gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
            gir1.2-webkit2-4.1=2.44.0-2 \
            xdg-utils

      - name: install dependencies (windows only)
        if: inputs.os == 'windows-latest'
        run: |
          choco install -y postgresql17

      - name: install dependencies (macos m1 only)
        if: inputs.os == 'macOS-latest' && inputs.target != 'x86_64-apple-darwin'
        run: |
          brew install postgresql@17

      - name: install dependencies (macos intel only)
        if: inputs.target == 'x86_64-apple-darwin'
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          arch -x86_64 /usr/local/bin/brew install postgresql@17

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: check NX cloud access
        id: nx-check
        continue-on-error: true
        run: pnpm nx noop

      - name: disable NX cloud
        if: steps.nx-check.outcome != 'success'
        run: echo "NX_NO_CLOUD=true" >> "$GITHUB_ENV"

      - name: install tauri cli
        run: cargo install tauri-cli --version "^2.0.0" --locked

      - name: build client
        env:
          CONFIGURATION: ${{ inputs.debug && 'debug' || 'release' }}
        run: |
          pnpm nx build retrom-client --args="$BUNDLE_ARG $TARGET_ARG $SIGN_ARG" --configuration="$CONFIGURATION"

      - name: upload build bundles
        id: bundles
        if: inputs.bundle
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_PREFIX }}bundles
          path: "${{ env.OUT_DIR }}/bundle"
          if-no-files-found: error

      - name: upload build artifact
        id: binary
        uses: actions/upload-artifact@v6
        env:
          BINARY_FILE: ${{ inputs.os == 'windows-latest' && 'Retrom.exe' || 'Retrom' }}
        with:
          name: ${{ env.ARTIFACT_PREFIX }}binary
          path: "${{ env.OUT_DIR }}/${{ env.BINARY_FILE }}"
          if-no-files-found: error

      - name: upload static web assets
        id: web-dist
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_PREFIX }}web-dist
          path: packages/client-web/dist/
          if-no-files-found: error

      - name: vendor cargo dependencies
        run: |
          cargo clean
          cargo vendor --locked --manifest-path packages/client/Cargo.toml

      - name: upload vendored cargo deps
        id: cargo-deps
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.ARTIFACT_PREFIX }}cargo-deps
          path: vendor/
          if-no-files-found: error
